class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'ar': {
      'welcome': 'مرحبًا بك في الألسن!',
      'intro': 'تعلم بسهولة مع دروس مصنفة',
      'start': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'home': 'الرئيسية',
      'profile': 'الملف الشخصي',
      'content': 'المحتوى',
      'chat': 'الشات',
      'results': 'النتائج',
      'help': 'المساعدة',
      'logout': 'تسجيل الخروج',
      'toggle_language': 'تغيير اللغة',
      'admin_users': 'إدارة المستخدمين',
      'upload_content': 'رفع المحتوى',
      'back': 'عودة',
      'name': 'الاسم',
      'code': 'الكود',
      'department': 'القسم',
      'schedule': 'جدول القسم',
      'title': 'العنوان',
      'pick_file': 'اختر ملف',
      'search': 'بحث',
      'message': 'رسالة',
      'student_id': 'رقم الجلوس',
      'view_results': 'عرض النتائج',
      'contact_us': 'تواصلوا معنا',
    },
    'en': {
      'welcome': 'Welcome to Alson!',
      'intro': 'Learn easily with categorized lessons',
      'start': 'Start Now',
      'login': 'Login',
      'username': 'Username',
      'password': 'Password',
      'home': 'Home',
      'profile': 'Profile',
      'content': 'Content',
      'chat': 'Chat',
      'results': 'Results',
      'help': 'Help',
      'logout': 'Logout',
      'toggle_language': 'Toggle Language',
      'admin_users': 'Manage Users',
      'upload_content': 'Upload Content',
      'back': 'Back',
      'name': 'Name',
      'code': 'Code',
      'department': 'Department',
      'schedule': 'Department Schedule',
      'title': 'Title',
      'pick_file': 'Pick File',
      'search': 'Search',
      'message': 'Message',
      'student_id': 'Student ID',
      'view_results': 'View Results',
      'contact_us': 'Contact Us',
    },
  };

  static String get(String key, String language) => _strings[language]![key] ?? key;
}